apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris
  namespace: tetris
  labels:
    app: tetris
spec:
  replicas: ${{ values.replicas }}
  selector:
    matchLabels:
      app: tetris
  template:
    metadata:
      labels:
        app: tetris
    spec:
      containers:
        - name: tetris
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
          resources:
            requests:
              cpu: "50m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"
      volumes:
        - name: html
          configMap:
            name: tetris-html
