apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.crossplane.io/stable
      chart: crossplane
      targetRevision: 2.2.1
      helm:
        valueFiles:
          - $values/infrastructure/crossplane/values.yaml
    - repoURL: https://github.com/Bruno94DB/devops_lab.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
