apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demoapps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Bruno94DB/devops_lab.git
    targetRevision: HEAD
    path: apps/demoapps
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
