global:
  domain: argocd.local

configs:
  params:
    server.insecure: "true"
  cm:
    # Allow ArgoCD to manage resources in all namespaces
    application.resourceTrackingMethod: annotation
  secret:
    argocdServerAdminPassword: "$2a$10$81jQlJtrQnyuRGbxoc4JpuTAjOmerF7TxQFTaGvSZNq43jsTFY.xq"

server:
  service:
    type: ClusterIP

# Single-replica setup for local lab (not HA)
redis-ha:
  enabled: false

controller:
  replicas: 1

repoServer:
  replicas: 1

applicationSet:
  replicas: 1
